GET http://localhost:5033/cart/
###
GET http://localhost:5033/products/
###
POST http://localhost:5033/cart/
content-type: application/json

{
    "product": "Peas",
    "price": 100
}
###
DELETE http://localhost:5033/cart/4
###
PUT http://localhost:5033/cart/2
content-type: application/json

{
    "id": 2,
    "product": "",
    "quantity": 1000
}

###
DELETE  http://localhost:5033/cart/
 
###
POST http://localhost:5033/login/
content-type: application/json

{
    "email":"teste",
    "password":"no"
}
###
GET http://localhost:5033/users/
###
GET http://localhost:5033/user/1/
###
POST http://localhost:5033/register/
content-type: application/json

{
    "credentials":{"email":"guest",
    "password":""},
    "confirmation":""
}